### ISSUE TITLE
Minified Rails/Unicorn startup failure

### ISSUE THREAD

**Issue by kcq** [cloudimmunity/docker-slim#15]
config.ru:1:in `<main>': cannot load such file -- rack/builder (LoadError)
        from /usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
        from /usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
        from /usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
        from /usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
        from /usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
        from /usr/local/bundle/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
        from /usr/local/bundle/bin/unicorn:16:in `load'
        from /usr/local/bundle/bin/unicorn:16:in `<main>'

Reported in this blog post:
http://chrisstump.online/2016/02/23/docker-image-reduction-techniques-and-tools/

Similar Rails app:
https://github.com/cstump/docker_example

**Comment by kcq** [comment]
An interesting way to setup containers. It makes it trickier to resolve the issue. Still working on it :)
